---
title: "Datentabellen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  options(scipen = 999)
)

source("data_1.R", encoding = 'UTF-8')
load("data/data_unpaywall.Rda")

library(kableExtra)
```

## Charité-Beteiligung: Jahr und OA-Status
```{r}
data_sum %>%
  kbl(align = "llll") %>%
  kable_styling() %>%
  scroll_box(width = "100%", height = "250px",
  box_css = "border: 1px solid #ddd; padding: 5px; "
)
```

## Charité Corresponding Author: Jahr und OA-Status
```{r}
data_corresponding_sum %>%
  kbl(align = "llll") %>%
  kable_styling() %>%
  scroll_box(width = "100%", height = "250px",
  box_css = "border: 1px solid #ddd; padding: 5px; "
)
```

## Charité-Beteiligung 2018-2020: Lizenzen und OA-Status
```{r}
load("data/data_license_oa_status_final_count_2.Rda")

data_license_oa_status_final_count_2 %>%
  kbl(align = "lll") %>%
  kable_styling() %>%
  scroll_box(width = "100", height = "250px",
  box_css = "border: 1px solid #ddd; padding: 5px; "
)
```

## Charité-Beteiligung 2020: Verlage und OA-Status
```{r}
data_publisher_table %>%
  kbl(align = "lll") %>%
  kable_styling() %>%
  scroll_box(width = "100", height = "250px",
  box_css = "border: 1px solid #ddd; padding: 5px; "
)
```
