---
title: "test"
author: "Jan Taubitz"
date: "9 6 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r, include=FALSE}
source("data_2.R", encoding = 'UTF-8')
```

```{r}
status_percent
```


```{r, include=FALSE}
raw_data <- read_excel("Endfassung.xlsx",
                       sheet = "Worksheet")

# raw_data <- read_excel("T:/OA-Dashboard/oa-dashboard/Endfassung.xlsx",
#                         sheet = "Worksheet")

########################### Clean data ###########################
data <- raw_data %>%
  clean_names() %>%
  mutate(oa_status = tolower(oa_status)) %>%
  mutate(oa_status = replace_na(oa_status, "kein ergebnis")) %>%
  mutate(oa_status = factor(oa_status, levels = c("green", "gold", "hybrid", "bronze", "closed", "kein ergebnis")))


########################### Exploratory visualizations ###########################


data_sum <- data %>%
  group_by(jahr, oa_status) %>%
  summarise(value = n()) %>%
  mutate(percentage = round(value / sum(value) * 100, 1))

color <- c("#5cff0a", "#ffdc0a", "#0ac7ff", "#cd7f32", "#262c2f", "darkgray")
text <- "In hac habitasse platea dictumst. Nam hendrerit elementum lacus. Suspendisse potenti. Vestibulum id aliquet neque. Praesent vel est est. Integer molestie consequat erat nec facilisis. Pellentesque scelerisque posuere nulla eu interdum."

hchart(
  data_sum,
  "column",
  hcaes(x = jahr, y = value, group = oa_status)
  ) %>%
  hc_plotOptions(series = list(stacking = "normal")) %>%
  hc_colors(color) %>%
  hc_title(text = "Open access status of articles in which Charité scientists were involved (in absolute numbers)", align = "left", style = list(fontSize = "28px")) %>%
  hc_subtitle(text = text, align = "left", style = list(fontSize = "16px"))

```

