---
title: "test"
author: "Jan Taubitz"
date: "9 6 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Row {data-height=auto}
-----------------------------------------------------------------------

### Analyse 3

<font size="5"> Median und Mittelwert der Zitierungen von den 2018 publizierten Artikeln mit Charité-Beteiligung (Daten von Crossref)</font>

Row 
-----------------------------------------------------------------------

###

```{r}
median_citation
```

###

```{r}
mean_citation
```


Row {data-height=100}
-----------------------------------------------------------------------

### Analyse 5

<font size="4"> Ein <b>Itemchart</b> zeigt jeden Artikel als einzelnen Punkt. Durch den Itemchart kann in einem Jahresvergleich gut die absolute Anzahl der Artikel repräsentiert als auch das prozentuale Verhältnis des OA-Status angezeigt werden.</font>


Row {data-height=150}
-----------------------------------------------------------------------

### 2018 - Open Access-Status von Artikeln mit Charité-Corresponding Author

```{r}
item_2018
```

Row {data-height=150}
-----------------------------------------------------------------------
### 2019 - Open Access-Status von Artikeln mit Charité-Corresponding Author

```{r}
item_2019
```
Row {data-height=200}
-----------------------------------------------------------------------
### 2020 - Open Access-Status von Artikeln mit Charité-Corresponding Author

```{r}
item_2020
```

